### ISSUE TITLE
Sort Issues

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/ygodeckprice#16]
Sort issues discovered on live version: https://ygoprodeck.com/card-database/deck-prices/

**Upvotes**: The highest up-voted card (Dark Magician) is not shown. 

**Latest**: Latest cards don't seem to be using the correct sorting methods. Seems to be a random mixture of cards.

**Comment by FelixRilling** [comment]
Should be fixed with aa70ec10fa09e72906121240350bd1391a68b02c
Some pretty old cards seem to have a rather new Timestamp in the .json I got from you
"A Legendary Ocean" -> "date":"2018-03-18 10:11:28"

**Comment by AlanOC91** [comment]
Ah you are looking at the "date" column in the json file. That's when the card was last called on the front-end.
